version: 2.1

orbs:
  ruby: circleci/ruby@1.1.3
  node: circleci/node@4.5.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn

  test:
    docker:
      - image: circleci/ruby:3.0.2-node
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:9.3
        environment:
          POSTGRES_USER: animagram
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: MyApp_test
    working_directory: ~/animagram
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Watting stand up database
          command: |
            dockerize -wait \
            tcp://127.0.0.1:5432 -timeout 10m
      - run: mv ./config/database.ci.yml ./config/database.yml
      - run:
          name: Database setup
          command: |
            bundle exec rails db:create db:migrate db:seed
      - ruby/rspec-test
      - ruby/rubocop-check

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
