default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ishidayurie
  password:
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: D-photo-app_development

test:
  <<: *default
  database: D-photo-app_test

production:
  <<: *default
  database: D-photo-app
